variable "region" {
  description = "AWS region to deploy the marketplace runtime."
  type        = string
}

variable "name" {
  description = "Prefix used for naming AWS resources."
  type        = string
  default     = "agnitra-marketplace"
}

variable "container_image" {
  description = "Container image reference for the Agnitra marketplace runtime."
  type        = string
}

variable "desired_count" {
  description = "Desired number of ECS tasks."
  type        = number
  default     = 2
}

variable "task_cpu" {
  description = "Fargate task CPU units."
  type        = number
  default     = 512
}

variable "task_memory" {
  description = "Fargate task memory (MB)."
  type        = number
  default     = 1024
}

variable "vpc_cidr" {
  description = "CIDR block for the autogenerated VPC."
  type        = string
  default     = "10.100.0.0/16"
}

variable "marketplace_product_code" {
  description = "AWS Marketplace product code used for SaaS metering."
  type        = string
}

variable "marketplace_usage_dimension" {
  description = "Usage dimension registered with the AWS Marketplace listing."
  type        = string
  default     = "RUNTIME_OPTIMIZATION_HOURS"
}

variable "environment" {
  description = "Additional environment variables injected into the container."
  type        = map(string)
  default     = {}
}

variable "autoscaling_max_capacity" {
  description = "Maximum number of tasks for autoscaling."
  type        = number
  default     = 6
}

variable "autoscaling_target_cpu" {
  description = "Target CPU utilization used by the scaling policy."
  type        = number
  default     = 60
}
